### PR TITLE
Displays the collection in the breadcrumbs when adding a new accession.

### PR DESCRIPTION
**Pull request by hectorcorrea**
Round two. The previous commit (6e1685fb92d0359b7eae93fa9e088ef21dfd3a37) was reverted by @awead because it was causing some sort of issue with Travis.

This version uses Solr to look for the collection (rather than hitting Fedora directly) and handles the possibility that the Collection might have not been indexed in Solr, in which case it displays "New Collection".

### CODE REVIEW

**Comment by awead** [comment]
The reason it was failing was that `default_collections_trail` was getting called at `/collections/new` when the collection hadn't been created yet:

https://github.com/psu-stewardship/archivesphere/blob/develop/app/controllers/concerns/breadcrumbs.rb#L33

The problem we're trying to address is displaying the collection name when visiting `/accession/new`. 

Try:
``` ruby
def add_collections_breadcrumb_for_accession
    if @accession.collections.empty? && params[:collection_id]
      add_breadcrumb collection_name_from_solr, collections.collection_path(params[:collection_id)
    else
      add_breadcrumb @accession.collections.first.title, collections.collection_path(@accession.collections.first)
    end
 end
```

**Comment by hectorcorrea** [comment]
@awead The new commit takes care of the problem. I've updated the code to query Solr (rather than Fedora) and gracefully handle the case where the collection might have not been Solrized.

**Comment by awead** [comment]
But you don't need the rescue.

**Comment by hectorcorrea** [comment]
On  a second thought, I would rather leave the code as-is. I don't think the breadcrumb should know anything about the fact that we are fetching the title from Solr vs Fedora. All it needs it's a title. 

This line
```
Collection.load_instance_from_solr("#{Sufia.config.id_namespace}:#{id}").title
```
would be a pretty bad code small in the breadcrumb code. The current code `Collection.title` seems cleaner. 

I could remove the check for the exception in the model if that is too bizarre, but it does not hurt anything to leave it there.

**Comment by awead** [comment]
I don't see that. I think having a class and instance method both named "title" is confusing. The most straight-forward way to get the title from the object using Solr is to use the methods that are already available on the object: "title" and "load_instance_from_solr".  If it were a standard Rails app, there would be no question. Arguably, the breadcrumb code shouldn't be in the controller to begin with and probably in the view instead, or another abstracted PORO, but that's a different discussion.

I also think it's a bad idea to put the rescue block in the model method. If the collection doesn't have a title, then it ought to fail because that's a problem. Putting the rescue in there obscures the underlying issue.

My point with all of this is that the simplest, most straight-forward fix, that uses the least amount of lines, modifies the fewest number of files, and creates the least amount of in-method branching is to just modify the Breadcrumb class. You could do it in two lines, one of them, albeit, a little long:

``` ruby
if @accession.collections.empty? && params[:collection_id]
      add_breadcrumb Collection.load_instance_from_solr("#{Sufia.config.id_namespace}:#{id}").title, collections.collection_path(params[:collection_id)
```

**Comment by cam156** [comment]
@awead I think that the code Hector has put in is reasonable.  
@hectorcorrea  I would suggest there are some tests missing.

**Comment by awead** [comment]
@cam156 the new accessions feature spec tests the presence of the breadcrumbs when creating new collections and accessions, so that should cover it.

**Pull request merged**
